//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="QT9.QMS.WebD.WS", ConfigurationName="ServiceReference.wsDocumentsSoap")]
    public interface wsDocumentsSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="QT9.QMS.WebD.WS/AddNewDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QTDocApprover))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QTDocCategory))]
        System.Threading.Tasks.Task<ServiceReference.AddNewDocumentResponse> AddNewDocumentAsync(ServiceReference.AddNewDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="QT9.QMS.WebD.WS/AddNewDocumentCategory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QTDocApprover))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QTDocCategory))]
        System.Threading.Tasks.Task<ServiceReference.AddNewDocumentCategoryResponse> AddNewDocumentCategoryAsync(ServiceReference.AddNewDocumentCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="QT9.QMS.WebD.WS/AddNewDocumentRevision", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QTDocApprover))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QTDocCategory))]
        System.Threading.Tasks.Task<ServiceReference.AddNewDocumentRevisionResponse> AddNewDocumentRevisionAsync(ServiceReference.AddNewDocumentRevisionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="QT9.QMS.WebD.WS/AddNewDocumentType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QTDocApprover))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QTDocCategory))]
        System.Threading.Tasks.Task<ServiceReference.AddNewDocumentTypeResponse> AddNewDocumentTypeAsync(ServiceReference.AddNewDocumentTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="QT9.QMS.WebD.WS/DocNumInUse", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QTDocApprover))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QTDocCategory))]
        System.Threading.Tasks.Task<ServiceReference.DocNumInUseResponse> DocNumInUseAsync(ServiceReference.DocNumInUseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="QT9.QMS.WebD.WS/GetAllDocumentsAsDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QTDocApprover))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QTDocCategory))]
        System.Threading.Tasks.Task<ServiceReference.GetAllDocumentsAsDataSetResponse> GetAllDocumentsAsDataSetAsync(ServiceReference.GetAllDocumentsAsDataSetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="QT9.QMS.WebD.WS/GetDocumentByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QTDocApprover))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QTDocCategory))]
        System.Threading.Tasks.Task<ServiceReference.GetDocumentByIDResponse> GetDocumentByIDAsync(ServiceReference.GetDocumentByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="QT9.QMS.WebD.WS/GetDocumentCategoriesAsDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QTDocApprover))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QTDocCategory))]
        System.Threading.Tasks.Task<ServiceReference.GetDocumentCategoriesAsDataSetResponse> GetDocumentCategoriesAsDataSetAsync(ServiceReference.GetDocumentCategoriesAsDataSetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="QT9.QMS.WebD.WS/GetDocumentRevisionByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QTDocApprover))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QTDocCategory))]
        System.Threading.Tasks.Task<ServiceReference.GetDocumentRevisionByIDResponse> GetDocumentRevisionByIDAsync(ServiceReference.GetDocumentRevisionByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="QT9.QMS.WebD.WS/GetDocumentTypesAsDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QTDocApprover))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QTDocCategory))]
        System.Threading.Tasks.Task<ServiceReference.GetDocumentTypesAsDataSetResponse> GetDocumentTypesAsDataSetAsync(ServiceReference.GetDocumentTypesAsDataSetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="QT9.QMS.WebD.WS/GetDocumentTypeByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QTDocApprover))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QTDocCategory))]
        System.Threading.Tasks.Task<ServiceReference.GetDocumentTypeByIDResponse> GetDocumentTypeByIDAsync(ServiceReference.GetDocumentTypeByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="QT9.QMS.WebD.WS/GetInvalidFileNameCharacters", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QTDocApprover))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QTDocCategory))]
        System.Threading.Tasks.Task<ServiceReference.GetInvalidFileNameCharactersResponse> GetInvalidFileNameCharactersAsync(ServiceReference.GetInvalidFileNameCharactersRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="QT9.QMS.WebD.WS")]
    public partial class wsAuthenticator
    {
        
        private string appTokenField;
        
        private string userNameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AppToken
        {
            get
            {
                return this.appTokenField;
            }
            set
            {
                this.appTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="QT9.QMS.WebD.WS")]
    public partial class QTDocType
    {
        
        private bool custRevNumField;
        
        private string doctypeField;
        
        private string doctypecodeField;
        
        private long doctypeidField;
        
        private bool isDeletedField;
        
        private bool inactiveField;
        
        private long numberingField;
        
        private long docReviewMonthsField;
        
        private string timelineField;
        
        private long numberOfApproversField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool CustRevNum
        {
            get
            {
                return this.custRevNumField;
            }
            set
            {
                this.custRevNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Doctype
        {
            get
            {
                return this.doctypeField;
            }
            set
            {
                this.doctypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Doctypecode
        {
            get
            {
                return this.doctypecodeField;
            }
            set
            {
                this.doctypecodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long Doctypeid
        {
            get
            {
                return this.doctypeidField;
            }
            set
            {
                this.doctypeidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool IsDeleted
        {
            get
            {
                return this.isDeletedField;
            }
            set
            {
                this.isDeletedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool Inactive
        {
            get
            {
                return this.inactiveField;
            }
            set
            {
                this.inactiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long Numbering
        {
            get
            {
                return this.numberingField;
            }
            set
            {
                this.numberingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public long docReviewMonths
        {
            get
            {
                return this.docReviewMonthsField;
            }
            set
            {
                this.docReviewMonthsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Timeline
        {
            get
            {
                return this.timelineField;
            }
            set
            {
                this.timelineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public long NumberOfApprovers
        {
            get
            {
                return this.numberOfApproversField;
            }
            set
            {
                this.numberOfApproversField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="QT9.QMS.WebD.WS")]
    public partial class QTDocApprover
    {
        
        private long databaseIDField;
        
        private string approverField;
        
        private long documentRevisionIDField;
        
        private bool approvedField;
        
        private string displayNameField;
        
        private long logonIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long DatabaseID
        {
            get
            {
                return this.databaseIDField;
            }
            set
            {
                this.databaseIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Approver
        {
            get
            {
                return this.approverField;
            }
            set
            {
                this.approverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long DocumentRevisionID
        {
            get
            {
                return this.documentRevisionIDField;
            }
            set
            {
                this.documentRevisionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool Approved
        {
            get
            {
                return this.approvedField;
            }
            set
            {
                this.approvedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DisplayName
        {
            get
            {
                return this.displayNameField;
            }
            set
            {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long LogonID
        {
            get
            {
                return this.logonIDField;
            }
            set
            {
                this.logonIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="QT9.QMS.WebD.WS")]
    public partial class QTDocumentRevision
    {
        
        private bool approvedField;
        
        private string approverField;
        
        private object[] approversField;
        
        private bool collabStartedField;
        
        private string commentsField;
        
        private long databaseIDField;
        
        private System.DateTime dateApprovedField;
        
        private System.DateTime targetCompletionField;
        
        private System.DateTime dateStampField;
        
        private string departmentsEffectedField;
        
        private string descriptionField;
        
        private string displayLocationField;
        
        private string documentAuthorField;
        
        private long documentIDField;
        
        private string locationField;
        
        private System.DateTime obsoleteDateField;
        
        private long publishedByIDField;
        
        private System.DateTime publishDateField;
        
        private string physicalLocationField;
        
        private int realRevNumField;
        
        private string rejectorField;
        
        private long rejectorIDField;
        
        private string requestorField;
        
        private long requestorIDField;
        
        private long respPartyIDField;
        
        private string revisionNumberField;
        
        private DocRequestStatus statusField;
        
        private string timeLineField;
        
        private bool trainingRequiredField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Approved
        {
            get
            {
                return this.approvedField;
            }
            set
            {
                this.approvedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Approver
        {
            get
            {
                return this.approverField;
            }
            set
            {
                this.approverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public object[] Approvers
        {
            get
            {
                return this.approversField;
            }
            set
            {
                this.approversField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool CollabStarted
        {
            get
            {
                return this.collabStartedField;
            }
            set
            {
                this.collabStartedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long DatabaseID
        {
            get
            {
                return this.databaseIDField;
            }
            set
            {
                this.databaseIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime DateApproved
        {
            get
            {
                return this.dateApprovedField;
            }
            set
            {
                this.dateApprovedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime TargetCompletion
        {
            get
            {
                return this.targetCompletionField;
            }
            set
            {
                this.targetCompletionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime DateStamp
        {
            get
            {
                return this.dateStampField;
            }
            set
            {
                this.dateStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string DepartmentsEffected
        {
            get
            {
                return this.departmentsEffectedField;
            }
            set
            {
                this.departmentsEffectedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string DisplayLocation
        {
            get
            {
                return this.displayLocationField;
            }
            set
            {
                this.displayLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string DocumentAuthor
        {
            get
            {
                return this.documentAuthorField;
            }
            set
            {
                this.documentAuthorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public long DocumentID
        {
            get
            {
                return this.documentIDField;
            }
            set
            {
                this.documentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public System.DateTime ObsoleteDate
        {
            get
            {
                return this.obsoleteDateField;
            }
            set
            {
                this.obsoleteDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public long PublishedByID
        {
            get
            {
                return this.publishedByIDField;
            }
            set
            {
                this.publishedByIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public System.DateTime PublishDate
        {
            get
            {
                return this.publishDateField;
            }
            set
            {
                this.publishDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string PhysicalLocation
        {
            get
            {
                return this.physicalLocationField;
            }
            set
            {
                this.physicalLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int RealRevNum
        {
            get
            {
                return this.realRevNumField;
            }
            set
            {
                this.realRevNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Rejector
        {
            get
            {
                return this.rejectorField;
            }
            set
            {
                this.rejectorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public long RejectorID
        {
            get
            {
                return this.rejectorIDField;
            }
            set
            {
                this.rejectorIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Requestor
        {
            get
            {
                return this.requestorField;
            }
            set
            {
                this.requestorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public long RequestorID
        {
            get
            {
                return this.requestorIDField;
            }
            set
            {
                this.requestorIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public long RespPartyID
        {
            get
            {
                return this.respPartyIDField;
            }
            set
            {
                this.respPartyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string RevisionNumber
        {
            get
            {
                return this.revisionNumberField;
            }
            set
            {
                this.revisionNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public DocRequestStatus Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string TimeLine
        {
            get
            {
                return this.timeLineField;
            }
            set
            {
                this.timeLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public bool TrainingRequired
        {
            get
            {
                return this.trainingRequiredField;
            }
            set
            {
                this.trainingRequiredField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="QT9.QMS.WebD.WS")]
    public enum DocRequestStatus
    {
        
        /// <remarks/>
        Submitted,
        
        /// <remarks/>
        Rejected,
        
        /// <remarks/>
        AlmostActive,
        
        /// <remarks/>
        Active,
        
        /// <remarks/>
        Obsolete,
        
        /// <remarks/>
        Canceled,
        
        /// <remarks/>
        Requested,
        
        /// <remarks/>
        Customer,
        
        /// <remarks/>
        Unknown,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="QT9.QMS.WebD.WS")]
    public partial class QTDocCategory
    {
        
        private long docCategoryIDField;
        
        private string docCategoryField;
        
        private string descriptionField;
        
        private bool inactiveField;
        
        private bool isDeletedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long DocCategoryID
        {
            get
            {
                return this.docCategoryIDField;
            }
            set
            {
                this.docCategoryIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DocCategory
        {
            get
            {
                return this.docCategoryField;
            }
            set
            {
                this.docCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool Inactive
        {
            get
            {
                return this.inactiveField;
            }
            set
            {
                this.inactiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool IsDeleted
        {
            get
            {
                return this.isDeletedField;
            }
            set
            {
                this.isDeletedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="QT9.QMS.WebD.WS")]
    public partial class QTDocument
    {
        
        private System.DateTime archiveDateField;
        
        private string changeNotesField;
        
        private long databaseIDField;
        
        private long docCategoryIDField;
        
        private long departmentIDField;
        
        private long docCatTypeIDField;
        
        private string docRefField;
        
        private string documentNameField;
        
        private long documentNumberField;
        
        private long documentTypeIDField;
        
        private object[] documentsAffectedField;
        
        private bool inactiveField;
        
        private bool isElectronicField;
        
        private System.DateTime originDateField;
        
        private System.DateTime previousReviewDateField;
        
        private long documentOwnerField;
        
        private object[] revisionsField;
        
        private System.DateTime scheduledReviewDateField;
        
        private long siteIDField;
        
        private string descriptionofDocField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime ArchiveDate
        {
            get
            {
                return this.archiveDateField;
            }
            set
            {
                this.archiveDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ChangeNotes
        {
            get
            {
                return this.changeNotesField;
            }
            set
            {
                this.changeNotesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long DatabaseID
        {
            get
            {
                return this.databaseIDField;
            }
            set
            {
                this.databaseIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long DocCategoryID
        {
            get
            {
                return this.docCategoryIDField;
            }
            set
            {
                this.docCategoryIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long DepartmentID
        {
            get
            {
                return this.departmentIDField;
            }
            set
            {
                this.departmentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long DocCatTypeID
        {
            get
            {
                return this.docCatTypeIDField;
            }
            set
            {
                this.docCatTypeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DocRef
        {
            get
            {
                return this.docRefField;
            }
            set
            {
                this.docRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string DocumentName
        {
            get
            {
                return this.documentNameField;
            }
            set
            {
                this.documentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public long DocumentNumber
        {
            get
            {
                return this.documentNumberField;
            }
            set
            {
                this.documentNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public long DocumentTypeID
        {
            get
            {
                return this.documentTypeIDField;
            }
            set
            {
                this.documentTypeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        public object[] DocumentsAffected
        {
            get
            {
                return this.documentsAffectedField;
            }
            set
            {
                this.documentsAffectedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool Inactive
        {
            get
            {
                return this.inactiveField;
            }
            set
            {
                this.inactiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool IsElectronic
        {
            get
            {
                return this.isElectronicField;
            }
            set
            {
                this.isElectronicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public System.DateTime OriginDate
        {
            get
            {
                return this.originDateField;
            }
            set
            {
                this.originDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public System.DateTime PreviousReviewDate
        {
            get
            {
                return this.previousReviewDateField;
            }
            set
            {
                this.previousReviewDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public long DocumentOwner
        {
            get
            {
                return this.documentOwnerField;
            }
            set
            {
                this.documentOwnerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=16)]
        public object[] Revisions
        {
            get
            {
                return this.revisionsField;
            }
            set
            {
                this.revisionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public System.DateTime ScheduledReviewDate
        {
            get
            {
                return this.scheduledReviewDateField;
            }
            set
            {
                this.scheduledReviewDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public long SiteID
        {
            get
            {
                return this.siteIDField;
            }
            set
            {
                this.siteIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string DescriptionofDoc
        {
            get
            {
                return this.descriptionofDocField;
            }
            set
            {
                this.descriptionofDocField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddNewDocument", WrapperNamespace="QT9.QMS.WebD.WS", IsWrapped=true)]
    public partial class AddNewDocumentRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="QT9.QMS.WebD.WS")]
        public ServiceReference.wsAuthenticator wsAuthenticator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="QT9.QMS.WebD.WS", Order=0)]
        public ServiceReference.QTDocument doc;
        
        public AddNewDocumentRequest()
        {
        }
        
        public AddNewDocumentRequest(ServiceReference.wsAuthenticator wsAuthenticator, ServiceReference.QTDocument doc)
        {
            this.wsAuthenticator = wsAuthenticator;
            this.doc = doc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddNewDocumentResponse", WrapperNamespace="QT9.QMS.WebD.WS", IsWrapped=true)]
    public partial class AddNewDocumentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="QT9.QMS.WebD.WS", Order=0)]
        public ServiceReference.QTDocument AddNewDocumentResult;
        
        public AddNewDocumentResponse()
        {
        }
        
        public AddNewDocumentResponse(ServiceReference.QTDocument AddNewDocumentResult)
        {
            this.AddNewDocumentResult = AddNewDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddNewDocumentCategory", WrapperNamespace="QT9.QMS.WebD.WS", IsWrapped=true)]
    public partial class AddNewDocumentCategoryRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="QT9.QMS.WebD.WS")]
        public ServiceReference.wsAuthenticator wsAuthenticator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="QT9.QMS.WebD.WS", Order=0)]
        public string DocCategory;
        
        public AddNewDocumentCategoryRequest()
        {
        }
        
        public AddNewDocumentCategoryRequest(ServiceReference.wsAuthenticator wsAuthenticator, string DocCategory)
        {
            this.wsAuthenticator = wsAuthenticator;
            this.DocCategory = DocCategory;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddNewDocumentCategoryResponse", WrapperNamespace="QT9.QMS.WebD.WS", IsWrapped=true)]
    public partial class AddNewDocumentCategoryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="QT9.QMS.WebD.WS", Order=0)]
        public long AddNewDocumentCategoryResult;
        
        public AddNewDocumentCategoryResponse()
        {
        }
        
        public AddNewDocumentCategoryResponse(long AddNewDocumentCategoryResult)
        {
            this.AddNewDocumentCategoryResult = AddNewDocumentCategoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddNewDocumentRevision", WrapperNamespace="QT9.QMS.WebD.WS", IsWrapped=true)]
    public partial class AddNewDocumentRevisionRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="QT9.QMS.WebD.WS")]
        public ServiceReference.wsAuthenticator wsAuthenticator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="QT9.QMS.WebD.WS", Order=0)]
        public ServiceReference.QTDocumentRevision DocRev;
        
        public AddNewDocumentRevisionRequest()
        {
        }
        
        public AddNewDocumentRevisionRequest(ServiceReference.wsAuthenticator wsAuthenticator, ServiceReference.QTDocumentRevision DocRev)
        {
            this.wsAuthenticator = wsAuthenticator;
            this.DocRev = DocRev;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddNewDocumentRevisionResponse", WrapperNamespace="QT9.QMS.WebD.WS", IsWrapped=true)]
    public partial class AddNewDocumentRevisionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="QT9.QMS.WebD.WS", Order=0)]
        public ServiceReference.QTDocumentRevision AddNewDocumentRevisionResult;
        
        public AddNewDocumentRevisionResponse()
        {
        }
        
        public AddNewDocumentRevisionResponse(ServiceReference.QTDocumentRevision AddNewDocumentRevisionResult)
        {
            this.AddNewDocumentRevisionResult = AddNewDocumentRevisionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddNewDocumentType", WrapperNamespace="QT9.QMS.WebD.WS", IsWrapped=true)]
    public partial class AddNewDocumentTypeRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="QT9.QMS.WebD.WS")]
        public ServiceReference.wsAuthenticator wsAuthenticator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="QT9.QMS.WebD.WS", Order=0)]
        public string DocType;
        
        public AddNewDocumentTypeRequest()
        {
        }
        
        public AddNewDocumentTypeRequest(ServiceReference.wsAuthenticator wsAuthenticator, string DocType)
        {
            this.wsAuthenticator = wsAuthenticator;
            this.DocType = DocType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddNewDocumentTypeResponse", WrapperNamespace="QT9.QMS.WebD.WS", IsWrapped=true)]
    public partial class AddNewDocumentTypeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="QT9.QMS.WebD.WS", Order=0)]
        public long AddNewDocumentTypeResult;
        
        public AddNewDocumentTypeResponse()
        {
        }
        
        public AddNewDocumentTypeResponse(long AddNewDocumentTypeResult)
        {
            this.AddNewDocumentTypeResult = AddNewDocumentTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DocNumInUse", WrapperNamespace="QT9.QMS.WebD.WS", IsWrapped=true)]
    public partial class DocNumInUseRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="QT9.QMS.WebD.WS")]
        public ServiceReference.wsAuthenticator wsAuthenticator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="QT9.QMS.WebD.WS", Order=0)]
        public int DocNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="QT9.QMS.WebD.WS", Order=1)]
        public long DocTypeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="QT9.QMS.WebD.WS", Order=2)]
        public long DepartmentID;
        
        public DocNumInUseRequest()
        {
        }
        
        public DocNumInUseRequest(ServiceReference.wsAuthenticator wsAuthenticator, int DocNum, long DocTypeID, long DepartmentID)
        {
            this.wsAuthenticator = wsAuthenticator;
            this.DocNum = DocNum;
            this.DocTypeID = DocTypeID;
            this.DepartmentID = DepartmentID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DocNumInUseResponse", WrapperNamespace="QT9.QMS.WebD.WS", IsWrapped=true)]
    public partial class DocNumInUseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="QT9.QMS.WebD.WS", Order=0)]
        public bool DocNumInUseResult;
        
        public DocNumInUseResponse()
        {
        }
        
        public DocNumInUseResponse(bool DocNumInUseResult)
        {
            this.DocNumInUseResult = DocNumInUseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllDocumentsAsDataSet", WrapperNamespace="QT9.QMS.WebD.WS", IsWrapped=true)]
    public partial class GetAllDocumentsAsDataSetRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="QT9.QMS.WebD.WS")]
        public ServiceReference.wsAuthenticator wsAuthenticator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="QT9.QMS.WebD.WS", Order=0)]
        public bool IncludeInactive;
        
        public GetAllDocumentsAsDataSetRequest()
        {
        }
        
        public GetAllDocumentsAsDataSetRequest(ServiceReference.wsAuthenticator wsAuthenticator, bool IncludeInactive)
        {
            this.wsAuthenticator = wsAuthenticator;
            this.IncludeInactive = IncludeInactive;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllDocumentsAsDataSetResponse", WrapperNamespace="QT9.QMS.WebD.WS", IsWrapped=true)]
    public partial class GetAllDocumentsAsDataSetResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="QT9.QMS.WebD.WS", Order=0)]
        public ServiceReference.ArrayOfXElement GetAllDocumentsAsDataSetResult;
        
        public GetAllDocumentsAsDataSetResponse()
        {
        }
        
        public GetAllDocumentsAsDataSetResponse(ServiceReference.ArrayOfXElement GetAllDocumentsAsDataSetResult)
        {
            this.GetAllDocumentsAsDataSetResult = GetAllDocumentsAsDataSetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDocumentByID", WrapperNamespace="QT9.QMS.WebD.WS", IsWrapped=true)]
    public partial class GetDocumentByIDRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="QT9.QMS.WebD.WS")]
        public ServiceReference.wsAuthenticator wsAuthenticator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="QT9.QMS.WebD.WS", Order=0)]
        public long DocID;
        
        public GetDocumentByIDRequest()
        {
        }
        
        public GetDocumentByIDRequest(ServiceReference.wsAuthenticator wsAuthenticator, long DocID)
        {
            this.wsAuthenticator = wsAuthenticator;
            this.DocID = DocID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDocumentByIDResponse", WrapperNamespace="QT9.QMS.WebD.WS", IsWrapped=true)]
    public partial class GetDocumentByIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="QT9.QMS.WebD.WS", Order=0)]
        public ServiceReference.QTDocument GetDocumentByIDResult;
        
        public GetDocumentByIDResponse()
        {
        }
        
        public GetDocumentByIDResponse(ServiceReference.QTDocument GetDocumentByIDResult)
        {
            this.GetDocumentByIDResult = GetDocumentByIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDocumentCategoriesAsDataSet", WrapperNamespace="QT9.QMS.WebD.WS", IsWrapped=true)]
    public partial class GetDocumentCategoriesAsDataSetRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="QT9.QMS.WebD.WS")]
        public ServiceReference.wsAuthenticator wsAuthenticator;
        
        public GetDocumentCategoriesAsDataSetRequest()
        {
        }
        
        public GetDocumentCategoriesAsDataSetRequest(ServiceReference.wsAuthenticator wsAuthenticator)
        {
            this.wsAuthenticator = wsAuthenticator;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDocumentCategoriesAsDataSetResponse", WrapperNamespace="QT9.QMS.WebD.WS", IsWrapped=true)]
    public partial class GetDocumentCategoriesAsDataSetResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="QT9.QMS.WebD.WS", Order=0)]
        public ServiceReference.ArrayOfXElement GetDocumentCategoriesAsDataSetResult;
        
        public GetDocumentCategoriesAsDataSetResponse()
        {
        }
        
        public GetDocumentCategoriesAsDataSetResponse(ServiceReference.ArrayOfXElement GetDocumentCategoriesAsDataSetResult)
        {
            this.GetDocumentCategoriesAsDataSetResult = GetDocumentCategoriesAsDataSetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDocumentRevisionByID", WrapperNamespace="QT9.QMS.WebD.WS", IsWrapped=true)]
    public partial class GetDocumentRevisionByIDRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="QT9.QMS.WebD.WS")]
        public ServiceReference.wsAuthenticator wsAuthenticator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="QT9.QMS.WebD.WS", Order=0)]
        public long DocRevID;
        
        public GetDocumentRevisionByIDRequest()
        {
        }
        
        public GetDocumentRevisionByIDRequest(ServiceReference.wsAuthenticator wsAuthenticator, long DocRevID)
        {
            this.wsAuthenticator = wsAuthenticator;
            this.DocRevID = DocRevID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDocumentRevisionByIDResponse", WrapperNamespace="QT9.QMS.WebD.WS", IsWrapped=true)]
    public partial class GetDocumentRevisionByIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="QT9.QMS.WebD.WS", Order=0)]
        public ServiceReference.QTDocumentRevision GetDocumentRevisionByIDResult;
        
        public GetDocumentRevisionByIDResponse()
        {
        }
        
        public GetDocumentRevisionByIDResponse(ServiceReference.QTDocumentRevision GetDocumentRevisionByIDResult)
        {
            this.GetDocumentRevisionByIDResult = GetDocumentRevisionByIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDocumentTypesAsDataSet", WrapperNamespace="QT9.QMS.WebD.WS", IsWrapped=true)]
    public partial class GetDocumentTypesAsDataSetRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="QT9.QMS.WebD.WS")]
        public ServiceReference.wsAuthenticator wsAuthenticator;
        
        public GetDocumentTypesAsDataSetRequest()
        {
        }
        
        public GetDocumentTypesAsDataSetRequest(ServiceReference.wsAuthenticator wsAuthenticator)
        {
            this.wsAuthenticator = wsAuthenticator;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDocumentTypesAsDataSetResponse", WrapperNamespace="QT9.QMS.WebD.WS", IsWrapped=true)]
    public partial class GetDocumentTypesAsDataSetResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="QT9.QMS.WebD.WS", Order=0)]
        public ServiceReference.ArrayOfXElement GetDocumentTypesAsDataSetResult;
        
        public GetDocumentTypesAsDataSetResponse()
        {
        }
        
        public GetDocumentTypesAsDataSetResponse(ServiceReference.ArrayOfXElement GetDocumentTypesAsDataSetResult)
        {
            this.GetDocumentTypesAsDataSetResult = GetDocumentTypesAsDataSetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDocumentTypeByID", WrapperNamespace="QT9.QMS.WebD.WS", IsWrapped=true)]
    public partial class GetDocumentTypeByIDRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="QT9.QMS.WebD.WS")]
        public ServiceReference.wsAuthenticator wsAuthenticator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="QT9.QMS.WebD.WS", Order=0)]
        public long DocTypeID;
        
        public GetDocumentTypeByIDRequest()
        {
        }
        
        public GetDocumentTypeByIDRequest(ServiceReference.wsAuthenticator wsAuthenticator, long DocTypeID)
        {
            this.wsAuthenticator = wsAuthenticator;
            this.DocTypeID = DocTypeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDocumentTypeByIDResponse", WrapperNamespace="QT9.QMS.WebD.WS", IsWrapped=true)]
    public partial class GetDocumentTypeByIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="QT9.QMS.WebD.WS", Order=0)]
        public ServiceReference.QTDocType GetDocumentTypeByIDResult;
        
        public GetDocumentTypeByIDResponse()
        {
        }
        
        public GetDocumentTypeByIDResponse(ServiceReference.QTDocType GetDocumentTypeByIDResult)
        {
            this.GetDocumentTypeByIDResult = GetDocumentTypeByIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInvalidFileNameCharacters", WrapperNamespace="QT9.QMS.WebD.WS", IsWrapped=true)]
    public partial class GetInvalidFileNameCharactersRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="QT9.QMS.WebD.WS")]
        public ServiceReference.wsAuthenticator wsAuthenticator;
        
        public GetInvalidFileNameCharactersRequest()
        {
        }
        
        public GetInvalidFileNameCharactersRequest(ServiceReference.wsAuthenticator wsAuthenticator)
        {
            this.wsAuthenticator = wsAuthenticator;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInvalidFileNameCharactersResponse", WrapperNamespace="QT9.QMS.WebD.WS", IsWrapped=true)]
    public partial class GetInvalidFileNameCharactersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="QT9.QMS.WebD.WS", Order=0)]
        public string[] GetInvalidFileNameCharactersResult;
        
        public GetInvalidFileNameCharactersResponse()
        {
        }
        
        public GetInvalidFileNameCharactersResponse(string[] GetInvalidFileNameCharactersResult)
        {
            this.GetInvalidFileNameCharactersResult = GetInvalidFileNameCharactersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface wsDocumentsSoapChannel : ServiceReference.wsDocumentsSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class wsDocumentsSoapClient : System.ServiceModel.ClientBase<ServiceReference.wsDocumentsSoap>, ServiceReference.wsDocumentsSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public wsDocumentsSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(wsDocumentsSoapClient.GetBindingForEndpoint(endpointConfiguration), wsDocumentsSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsDocumentsSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(wsDocumentsSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsDocumentsSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(wsDocumentsSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsDocumentsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.AddNewDocumentResponse> ServiceReference.wsDocumentsSoap.AddNewDocumentAsync(ServiceReference.AddNewDocumentRequest request)
        {
            return base.Channel.AddNewDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.AddNewDocumentResponse> AddNewDocumentAsync(ServiceReference.wsAuthenticator wsAuthenticator, ServiceReference.QTDocument doc)
        {
            ServiceReference.AddNewDocumentRequest inValue = new ServiceReference.AddNewDocumentRequest();
            inValue.wsAuthenticator = wsAuthenticator;
            inValue.doc = doc;
            return ((ServiceReference.wsDocumentsSoap)(this)).AddNewDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.AddNewDocumentCategoryResponse> ServiceReference.wsDocumentsSoap.AddNewDocumentCategoryAsync(ServiceReference.AddNewDocumentCategoryRequest request)
        {
            return base.Channel.AddNewDocumentCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.AddNewDocumentCategoryResponse> AddNewDocumentCategoryAsync(ServiceReference.wsAuthenticator wsAuthenticator, string DocCategory)
        {
            ServiceReference.AddNewDocumentCategoryRequest inValue = new ServiceReference.AddNewDocumentCategoryRequest();
            inValue.wsAuthenticator = wsAuthenticator;
            inValue.DocCategory = DocCategory;
            return ((ServiceReference.wsDocumentsSoap)(this)).AddNewDocumentCategoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.AddNewDocumentRevisionResponse> ServiceReference.wsDocumentsSoap.AddNewDocumentRevisionAsync(ServiceReference.AddNewDocumentRevisionRequest request)
        {
            return base.Channel.AddNewDocumentRevisionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.AddNewDocumentRevisionResponse> AddNewDocumentRevisionAsync(ServiceReference.wsAuthenticator wsAuthenticator, ServiceReference.QTDocumentRevision DocRev)
        {
            ServiceReference.AddNewDocumentRevisionRequest inValue = new ServiceReference.AddNewDocumentRevisionRequest();
            inValue.wsAuthenticator = wsAuthenticator;
            inValue.DocRev = DocRev;
            return ((ServiceReference.wsDocumentsSoap)(this)).AddNewDocumentRevisionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.AddNewDocumentTypeResponse> ServiceReference.wsDocumentsSoap.AddNewDocumentTypeAsync(ServiceReference.AddNewDocumentTypeRequest request)
        {
            return base.Channel.AddNewDocumentTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.AddNewDocumentTypeResponse> AddNewDocumentTypeAsync(ServiceReference.wsAuthenticator wsAuthenticator, string DocType)
        {
            ServiceReference.AddNewDocumentTypeRequest inValue = new ServiceReference.AddNewDocumentTypeRequest();
            inValue.wsAuthenticator = wsAuthenticator;
            inValue.DocType = DocType;
            return ((ServiceReference.wsDocumentsSoap)(this)).AddNewDocumentTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.DocNumInUseResponse> ServiceReference.wsDocumentsSoap.DocNumInUseAsync(ServiceReference.DocNumInUseRequest request)
        {
            return base.Channel.DocNumInUseAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.DocNumInUseResponse> DocNumInUseAsync(ServiceReference.wsAuthenticator wsAuthenticator, int DocNum, long DocTypeID, long DepartmentID)
        {
            ServiceReference.DocNumInUseRequest inValue = new ServiceReference.DocNumInUseRequest();
            inValue.wsAuthenticator = wsAuthenticator;
            inValue.DocNum = DocNum;
            inValue.DocTypeID = DocTypeID;
            inValue.DepartmentID = DepartmentID;
            return ((ServiceReference.wsDocumentsSoap)(this)).DocNumInUseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.GetAllDocumentsAsDataSetResponse> ServiceReference.wsDocumentsSoap.GetAllDocumentsAsDataSetAsync(ServiceReference.GetAllDocumentsAsDataSetRequest request)
        {
            return base.Channel.GetAllDocumentsAsDataSetAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.GetAllDocumentsAsDataSetResponse> GetAllDocumentsAsDataSetAsync(ServiceReference.wsAuthenticator wsAuthenticator, bool IncludeInactive)
        {
            ServiceReference.GetAllDocumentsAsDataSetRequest inValue = new ServiceReference.GetAllDocumentsAsDataSetRequest();
            inValue.wsAuthenticator = wsAuthenticator;
            inValue.IncludeInactive = IncludeInactive;
            return ((ServiceReference.wsDocumentsSoap)(this)).GetAllDocumentsAsDataSetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.GetDocumentByIDResponse> ServiceReference.wsDocumentsSoap.GetDocumentByIDAsync(ServiceReference.GetDocumentByIDRequest request)
        {
            return base.Channel.GetDocumentByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.GetDocumentByIDResponse> GetDocumentByIDAsync(ServiceReference.wsAuthenticator wsAuthenticator, long DocID)
        {
            ServiceReference.GetDocumentByIDRequest inValue = new ServiceReference.GetDocumentByIDRequest();
            inValue.wsAuthenticator = wsAuthenticator;
            inValue.DocID = DocID;
            return ((ServiceReference.wsDocumentsSoap)(this)).GetDocumentByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.GetDocumentCategoriesAsDataSetResponse> ServiceReference.wsDocumentsSoap.GetDocumentCategoriesAsDataSetAsync(ServiceReference.GetDocumentCategoriesAsDataSetRequest request)
        {
            return base.Channel.GetDocumentCategoriesAsDataSetAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.GetDocumentCategoriesAsDataSetResponse> GetDocumentCategoriesAsDataSetAsync(ServiceReference.wsAuthenticator wsAuthenticator)
        {
            ServiceReference.GetDocumentCategoriesAsDataSetRequest inValue = new ServiceReference.GetDocumentCategoriesAsDataSetRequest();
            inValue.wsAuthenticator = wsAuthenticator;
            return ((ServiceReference.wsDocumentsSoap)(this)).GetDocumentCategoriesAsDataSetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.GetDocumentRevisionByIDResponse> ServiceReference.wsDocumentsSoap.GetDocumentRevisionByIDAsync(ServiceReference.GetDocumentRevisionByIDRequest request)
        {
            return base.Channel.GetDocumentRevisionByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.GetDocumentRevisionByIDResponse> GetDocumentRevisionByIDAsync(ServiceReference.wsAuthenticator wsAuthenticator, long DocRevID)
        {
            ServiceReference.GetDocumentRevisionByIDRequest inValue = new ServiceReference.GetDocumentRevisionByIDRequest();
            inValue.wsAuthenticator = wsAuthenticator;
            inValue.DocRevID = DocRevID;
            return ((ServiceReference.wsDocumentsSoap)(this)).GetDocumentRevisionByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.GetDocumentTypesAsDataSetResponse> ServiceReference.wsDocumentsSoap.GetDocumentTypesAsDataSetAsync(ServiceReference.GetDocumentTypesAsDataSetRequest request)
        {
            return base.Channel.GetDocumentTypesAsDataSetAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.GetDocumentTypesAsDataSetResponse> GetDocumentTypesAsDataSetAsync(ServiceReference.wsAuthenticator wsAuthenticator)
        {
            ServiceReference.GetDocumentTypesAsDataSetRequest inValue = new ServiceReference.GetDocumentTypesAsDataSetRequest();
            inValue.wsAuthenticator = wsAuthenticator;
            return ((ServiceReference.wsDocumentsSoap)(this)).GetDocumentTypesAsDataSetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.GetDocumentTypeByIDResponse> ServiceReference.wsDocumentsSoap.GetDocumentTypeByIDAsync(ServiceReference.GetDocumentTypeByIDRequest request)
        {
            return base.Channel.GetDocumentTypeByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.GetDocumentTypeByIDResponse> GetDocumentTypeByIDAsync(ServiceReference.wsAuthenticator wsAuthenticator, long DocTypeID)
        {
            ServiceReference.GetDocumentTypeByIDRequest inValue = new ServiceReference.GetDocumentTypeByIDRequest();
            inValue.wsAuthenticator = wsAuthenticator;
            inValue.DocTypeID = DocTypeID;
            return ((ServiceReference.wsDocumentsSoap)(this)).GetDocumentTypeByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.GetInvalidFileNameCharactersResponse> ServiceReference.wsDocumentsSoap.GetInvalidFileNameCharactersAsync(ServiceReference.GetInvalidFileNameCharactersRequest request)
        {
            return base.Channel.GetInvalidFileNameCharactersAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.GetInvalidFileNameCharactersResponse> GetInvalidFileNameCharactersAsync(ServiceReference.wsAuthenticator wsAuthenticator)
        {
            ServiceReference.GetInvalidFileNameCharactersRequest inValue = new ServiceReference.GetInvalidFileNameCharactersRequest();
            inValue.wsAuthenticator = wsAuthenticator;
            return ((ServiceReference.wsDocumentsSoap)(this)).GetInvalidFileNameCharactersAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsDocumentsSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.wsDocumentsSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsDocumentsSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://mybinxhealth.qt9qms.app/services/wsDocuments.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.wsDocumentsSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://mybinxhealth.qt9qms.app/services/wsDocuments.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            wsDocumentsSoap,
            
            wsDocumentsSoap12,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil-lib", "2.1.0.0")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
